name: 'From 1 job to N jobs'

on:
  push:
    paths: [ '.github/workflows/1-to-n.yml' ]
  pull_request:
    paths: [ '.github/workflows/1-to-n.yml' ]

jobs:
  job-a:
    name: Job A
    runs-on: ubuntu-latest
    steps:
      - run: true

  job-b:
    name: Job B
    runs-on: ubuntu-latest
    needs: job-a
    steps:
      - run: true

  job-c:
    name: Job C
    runs-on: ubuntu-latest
    needs: job-a
    steps:
      - run: true
