name: 'Dynamic matrices'

on:
  push:
    paths: [ '.github/workflows/dynamic-matrices.yml' ]
  pull_request_target:
    paths: [ '.github/workflows/dynamic-matrices.yml' ]

jobs:
  generate-matrix:
    name: Generate
    runs-on: ubuntu-latest
    outputs:
      json: ${{ steps.generate.outputs.json }}
    steps:
      - id: generate
        run: |
          ITEMS=('a' 'b' 'c')

          JSON=$(printf '%s\n' "${ITEMS[@]}" | jq -R . | jq -sc .)
          echo $JSON

          echo "::set-output name=json::$JSON"

  dynamic:
    name: Dynamic
    runs-on: ubuntu-latest
    needs: generate-matrix
    strategy:
      matrix:
        items: ${{ fromJson(needs.generate-matrix.outputs.json) }}
    steps:
      - run: true

  hybrid:
    name: Hybrid
    runs-on: ubuntu-latest
    needs: generate-matrix
    strategy:
      matrix:
        items: ${{ fromJson(needs.generate-matrix.outputs.json) }}
        options: ['a', 'b']
    steps:
      - run: true

  hybrid-exlusions:
    name: 'Hybrid w/ exclusions'
    runs-on: ubuntu-latest
    needs: generate-matrix
    strategy:
      matrix:
        items: ${{ fromJson(needs.generate-matrix.outputs.json) }}
        options: ['a', 'b']
        exclude:
          - items: 'a'
          - items: 'b'
            options: 'b'
    steps:
      - run: true

  hybrid-exclusion-inclusions:
    name: 'Hybrid w/ exclusions/inclusions'
    runs-on: ubuntu-latest
    needs: generate-matrix
    strategy:
      matrix:
        items: ${{ fromJson(needs.generate-matrix.outputs.json) }}
        options: ['a', 'b']
        exclude:
          - items: 'a'
          - items: 'b'
            options: 'b'
        include:
          - items: 'd'
          - items: 'e'
            options: 'c'
    steps:
      - run: true
